[package]
name = "nu_plugin_dbus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dbus = "0.9.7"
nu-plugin = "0.89.0"
nu-protocol = { version = "0.89.0", features = ["plugin"] }
